Jahia/cloud-scripts

- remove-passwords/remove-passwords.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-526
Little script to clear jahia root and tools passwords
> PAAS-526: clear jahia root and tools passwords

- jahia-cloud-env-update/update-to-1.2/jahia_logrotate
- jahia-cloud-env-update/update-to-1.2/logging.properties
- jahia-cloud-env-update/update-to-1.2/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-758
jahia cloud environment update to 1.2
> jahia-cloud-update-to-1.2

- jahia-cloud-env-update/update-to-1.2/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-758
Also added some logging
> jahia-cloud-update-to-1.2: Adding tomcat conf saving for redeploy

- jahia-cloud-env-update/update-to-1.3/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-869
> PAAS-869: update script to 1.3

- jahia-cloud-env-update/update-to-1.3/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-869
> PAAS-869: disable useless steps in update script to 1.3

- jahia-cloud-env-update/update-to-1.4/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-357
> PAAS-357 update datadog's mysql integration conf

- jahia-cloud-env-update/update-to-1.4/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-902
- Fix user
> PAAS-902: Fix user

- jahia-cloud-env-update/update-to-1.4/org.jahia.modules.api.permissions-tuto.cfg
JIRA issue: https://jira.jahia.org/browse/PAAS-902
- Extend GraphQL permissions
> PAAS-902: Extend GraphQL permissions

- thread-dump/thread-dump.sh
JIRA issue: https://jira.jahia.org/browse/COPS-31
> COPS-31: fix user for jstack

- jahia-cloud-env-update/update-to-1.5/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-959
> PAAS-959: adding 1.5 update script with haproxy upgrade

- jahia-cloud-env-update/update-to-1.4/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-959
> PAAS-959: missing globals (I am stupid)

- jahia-cloud-env-update/update-to-1.4/update-fix.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-959
> PAAS-959: adding fix script following haproxy redeploy oversights

- restart-galera-nodes/restart-galera-nodes.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1005
> SAAS-1005 restart mariadb nodes using jahia's full readonly mode

- remove-passwords/remove-passwords.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-67
> COPS-67: remove passwords

- jahia-cloud-env-update/update-to-2.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-897
Short description: that's for the updating already here envs
> PAAS-897 check ES before start karaf daemon

- jahia-cloud-env-update/update-to-2.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1078
> Paas 1078 haproxy rule for healthcheck

- jahia-cloud-env-update/update-to-2.1.0/redeploy_es_mariadb.yml
- jahia-cloud-env-update/update-to-2.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1087
> Paas 1087 persist es data

- jahia-cloud-env-update/update-to-2.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1084
> PAAS-1084: allow jCustomer to start when ES status is yellow

- jahia-cloud-env-update/update-to-2.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1093
> PAAS-1093: add max open files limit for mariadb [2.1.0 release]

- archives/fix-haproxy-init-script.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-97
> COPS-97: fix haproxy init script

- restart-galera-nodes/restart-galera-nodes.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1079
> PAAS-1079: improve galera restart

- jahia-cloud-env-update/update-to-2.1.0/haproxy-11-proc.cfg
- jahia-cloud-env-update/update-to-2.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1123
> PAAS-1123: configure direct access to processing on haproxy

- jahia-cloud-env-update/update-to-2.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1093
> PAAS-1093: fix fixMariaDbMaxOpenFiles action and jps id

- jahia-cloud-env-update/update-to-2.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-495
> PAAS-495: enable checkForwardedHeaders in osgi

- archives/fix-datadog-conf-haproxy.yml
JIRA issue: https://jira.jahia.org/browse/COPS-129
> COPS-129: add jps to fix DD conf on old envs' haproxy nodes

- jahia-cloud-env-update/update-to-2.3.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1228
> PAAS-1228: fix datadog hostname for ES nodes

- es-nodes/redeploy-es-nodes.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1200
> PAAS-1200: add cluster healtcheck to ES redeploy

- jahia-cloud-env-update/update-to-2.3.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1045
> PAAS-1045: disable direct node access [release 2.3.0]

- jahia-cloud-env-update/update-to-2.3.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1247
> PAAS-1247: disable checkForwardedHeaders

- jahia-cloud-env-update/update-to-2.4.0/dd_agent_jelastic_package_conf.yml
- jahia-cloud-env-update/update-to-2.4.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1237
> PAAS-1237: jelastic package logging

- jahia-cloud-env-update/update-to-2.4.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1237
> PAAS-1237: fix permissions on backup log file

- jahia-cloud-env-update/update-to-2.1.0/update-fix.yml
- jahia-cloud-env-update/update-to-2.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1251
> PAAS-1251: fix jcustomer execprestart

- utils/disable-proxysql.yml
- utils/setup-proxysql.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1265
> PAAS-1265: add ProxySQL setup & disable packages

- utils/setup-proxysql.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1265
> PAAS-1265: fix proxysql check

- jahia-cloud-env-update/update-to-2.4.0/haproxy-backend-healthcheck.sh
- jahia-cloud-env-update/update-to-2.4.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1271
> PAAS-1271: protect healthcheck with token

- jahia-cloud-env-update/update-to-3.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1281
> PAAS-1281: Remove tomcat restart (operation is duplicated)

- jahia-cloud-env-update/update-to-3.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1281
> PAAS-1281: Fix jahia nodes restart 

- utils/dont_use_read_rule-proxysql.yml
- utils/setup-proxysql.yml
JIRA issue: https://jira.jahia.org/browse/COPS-201
> COPS-201: disable query rule to readers hostgroup

- jahia-cloud-env-update/update-to-3.2.0/dd_agent_haproxy_conf_new_lines.yml
- jahia-cloud-env-update/update-to-3.2.0/logrotate_haproxy
- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1283
> PAAS-1283: fix haproxy logrotate and add haproxy status logs to datadog

- .github/CODEOWNERS
- .github/pull_request_template.md
- es-nodes/redeploy-es-nodes.yml
JIRA issue: https://jira.jahia.org/browse/COPS-206
> Cops 206 fix es redeploy

- jahia-cloud-env-update/update-to-3.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/CCM-47
> CCM-47: Add all needed action to v3.1.0 update package

- jahia-cloud-env-update/update-to-3.1.0/update.yml
JIRA issue: https://jira.jahia.org/browse/CCM-47
> CCM-47: fix update script (bug with Jelastic API call)

- jahia-cloud-env-update/update-to-3.1.0/haproxy-backend-healthcheck.sh
JIRA issue: https://jira.jahia.org/browse/COPS-210
> COPS-210: Fix healthcheck URL

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1230
> PAAS-1230: fix jahia.properties to envvars action [update 3.0.2]

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/COPS-1230
> PAAS-1230: fix jahia.properties to envvars (again) [update-3.2.0]

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/COPS-1319
> PAAS-1319: define (bigger) galera cache size & restart nodes [update-3.2.0]

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1230
> PAAS-1230: new fix for jahia.properties to envvars [update-3.2.0]

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1282
Add HTTP Security Response Headers at HAProxy level on update
> PAAS-1282: Add HTTP Security Headers to Haproxy  on update

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1319
> PAAS-1319: fix galera cache action [update-3.2.0]

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1308
> PAAS-1308: fix haproxy healthcheck path [update-3.2.0]

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1324
> PAAS-1324: allow YELLOW for haproxy healthcheck [update-3.2.0]

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/COPS-1324
> PAAS-1324: fix allowYellowHaproxyHealthcheck not called [update-3.2.0]

- archives/upgrade-healthcheck.yml
JIRA issue: https://jira.jahia.org/browse/COPS-225
> COPS-225: add script to update jahia 7.3.X.X healthcheck to 1.1.0

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1324
> PAAS-1324: fix allowYellowHaproxyHealthcheck cmd [update-3.2.0]

- archives/upgrade-healthcheck.yml
JIRA issue: https://jira.jahia.org/browse/COPS-225
> COPS-225: improve idempotence in update-healthcheck script

- archives/upgrade-healthcheck.yml
JIRA issue: https://jira.jahia.org/browse/COPS-225
> COPS-225: update-healthcheck script now start the module if not

- archives/upgrade-healthcheck.yml
JIRA issue: https://jira.jahia.org/browse/COPS-225
> COPS-225: update-healthcheck script fix typo

- jahia-cloud-env-update/update-to-3.2.0/update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1292
> PAAS-1292: generate vault credentials for 3.2.0 update script

- augmented-search/augsearch-redeploy-es-nodes.yml
- es-nodes/redeploy-es-nodes.yml
- galera-nodes/redeploy-galera-nodes.yml
- galera-nodes/restart-galera-nodes.yml
JIRA issue: https://jira.jahia.org/browse/COPS-213
> COPS-213: Add package to redeploy Augmented Search's ES nodes

- archives/fix-vault-env-var.yml
JIRA issue: https://jira.jahia.org/browse/COPS-244
> COPS-244: fix vault env var

- utils/update-datadog-apikey.yml
JIRA issue: https://jira.jahia.org/browse/COPS-232
> COPS-232: Update the DATADOGAPIKEY envvar for environments

- utils/move-one-node.yml
JIRA issue: https://jira.jahia.org/browse/COPS-253
> COPS-253 fix disable FRO not working

- jahia/mixins-jahia.yml
JIRA issue: https://jira.jahia.org/browse/COPS-253
> COPS-253 add loop checking ssh connexion in is_fullreadonly_enabled

- jahia/mixins-jahia.yml
JIRA issue: https://jira.jahia.org/browse/COPS-253
> COPS-253 fix silly standard output in loop

- one-shot/fix-imagemagick.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1468
> PAAS-1468 fix imagemagick not working after migration to v3.0.0

- utils/move-one-node.yml
JIRA issue: https://jira.jahia.org/browse/COPS-276
> COPS-276 replace API's admin method by static lists

- one-shot/fix-dd-agent-jvm-metrics.yml
JIRA issue: https://jira.jahia.org/browse/COPS-1478
> PAAS-1478: add package to fix JVM metrics not sent on Tomcat nodes
